version: "3"
services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    networks:
      - default
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal