version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./code:/code
      - ./xdebug.conf:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - code-network
    environment:
      PHP_EXTENSION_XDEBUG: 1

  composer:
    image: composer:latest
    command: install
    volumes:
      - ./code:/app

networks:
  code-network:
    driver: bridge